import type { CountrySeed } from "../lib/types";

export const italy: CountrySeed = {
  code: "IT",
  name: "Italy",
  continent: "Europe",
  region: "Southern Europe",
  currency: "EUR",
  languages: ["it", "en"],
  timezoneOffsets: ["UTC+1", "UTC+2"],
  avgCostPerDayUsd: 85,
  safetyIndex: 7.8,
  visaOnArrival: [],
  bestMonths: [4, 5, 9, 10],
  experiences: [
    { category: "food", name: "Trastevere Food Tour", city: "Rome", lat: 41.889, lng: 12.469, cost: 85, hours: 3.5, pop: 9.2, desc: "Evening walking tour through Rome's most beloved food quarter — supplì, porchetta, gelato." },
    { category: "food", name: "Fresh Pasta Workshop", city: "Bologna", lat: 44.494, lng: 11.343, cost: 70, hours: 3, pop: 9.0, desc: "Hand-roll tagliatelle and tortellini with a sfoglina in the food capital of Italy." },
    { category: "food", name: "Truffle Hunting in Alba", city: "Alba", lat: 44.7, lng: 8.035, cost: 140, hours: 4, pop: 8.7, desc: "Hunt white truffles with a trifolau and his dog, then a tasting lunch in the Langhe hills." },
    { category: "food", name: "Naples Pizza Pilgrimage", city: "Naples", lat: 40.851, lng: 14.268, cost: 35, hours: 2.5, pop: 9.5, desc: "The originals: Da Michele, Sorbillo, and wood-fired margherita where pizza was born." },
    { category: "food", name: "Chianti Wine Estate Tasting", city: "Siena", lat: 43.318, lng: 11.33, cost: 95, hours: 5, pop: 8.9, desc: "Drive the SR222 through vineyards, tasting Chianti Classico at two family estates." },
    { category: "food_festival", name: "Palermo Street Food Crawl", city: "Palermo", lat: 38.116, lng: 13.361, cost: 45, hours: 3, pop: 8.8, desc: "Arancine, panelle, and sfincione through the Ballarò and Vucciria markets." },
    { category: "hike", name: "Cinque Terre Coastal Trail", city: "Cinque Terre", lat: 44.127, lng: 9.71, cost: 8, hours: 5, pop: 9.4, desc: "The Sentiero Azzurro between five pastel villages clinging to the Ligurian cliffs." },
    { category: "hike", name: "Tre Cime di Lavaredo Loop", city: "Dolomites", lat: 46.618, lng: 12.302, cost: 30, hours: 4, pop: 9.6, desc: "The most iconic hike in the Dolomites — a 10km loop around three colossal peaks." },
    { category: "nature", name: "Saturnia Hot Springs", city: "Saturnia", lat: 42.649, lng: 11.512, cost: 0, hours: 3, pop: 8.5, desc: "Free cascading thermal pools in the Tuscan Maremma. Go at sunrise." },
    { category: "hike", name: "Path of the Gods", city: "Amalfi", lat: 40.634, lng: 14.602, cost: 0, hours: 4, pop: 9.3, desc: "Cliffside trail from Bomerano to Nocelle, suspended above the Amalfi Coast." },
    { category: "scenic", name: "Lake Como Villa Circuit", city: "Como", lat: 45.985, lng: 9.257, cost: 40, hours: 6, pop: 9.0, desc: "Ferry-hop between Bellagio, Varenna, and Villa del Balbianello's gardens." },
    { category: "city", name: "Colosseum & Roman Forum", city: "Rome", lat: 41.89, lng: 12.492, cost: 18, hours: 4, pop: 9.7, desc: "Underground-and-arena access tour of the ancient heart of the empire." },
    { category: "city", name: "Uffizi Gallery", city: "Florence", lat: 43.768, lng: 11.255, cost: 26, hours: 3, pop: 9.5, desc: "Botticelli, Caravaggio, da Vinci — the Renaissance under one roof." },
    { category: "city", name: "Venice: San Marco & Gondola", city: "Venice", lat: 45.434, lng: 12.339, cost: 95, hours: 4, pop: 9.1, desc: "Basilica mosaics, Doge's Palace, and a back-canal gondola at golden hour." },
    { category: "city", name: "Pompeii with Archaeologist", city: "Naples", lat: 40.749, lng: 14.485, cost: 55, hours: 4, pop: 9.4, desc: "The frozen Roman city, guided by a working archaeologist. Vesuvius add-on." },
    { category: "concert", name: "Opera at Arena di Verona", city: "Verona", lat: 45.439, lng: 10.994, cost: 60, hours: 4, pop: 9.2, desc: "Aida under the stars in a 2,000-year-old Roman amphitheatre." },
    { category: "music", name: "Umbria Jazz Evening", city: "Perugia", lat: 43.112, lng: 12.389, cost: 40, hours: 4, pop: 8.6, desc: "Europe's great jazz festival takes over Perugia's medieval streets each July." },
    { category: "concert", name: "Teatro San Carlo Performance", city: "Naples", lat: 40.837, lng: 14.249, cost: 50, hours: 3, pop: 8.4, desc: "Europe's oldest working opera house, gilded and gorgeous." },
    { category: "beach", name: "Positano Beach Day", city: "Amalfi", lat: 40.628, lng: 14.485, cost: 30, hours: 5, pop: 8.9, desc: "Spiaggia Grande sunbeds, cliff-jumping at Fornillo, Aperol at sunset." },
    { category: "swimming", name: "Capri Blue Grotto Swim", city: "Capri", lat: 40.561, lng: 14.205, cost: 75, hours: 6, pop: 9.0, desc: "Boat circuit of the island with a swim stop in electric-blue sea caves." },
    { category: "beach", name: "San Vito Lo Capo", city: "Sicily", lat: 38.174, lng: 12.735, cost: 15, hours: 6, pop: 8.7, desc: "Caribbean-clear water beneath Monte Monaco on Sicily's northwest tip." },
    { category: "nightlife", name: "Navigli Aperitivo Crawl", city: "Milan", lat: 45.452, lng: 9.176, cost: 35, hours: 3, pop: 8.3, desc: "Canal-side spritz culture — pay for a drink, eat the buffet." },
    { category: "photography", name: "Val d'Orcia at Dawn", city: "Siena", lat: 43.06, lng: 11.69, cost: 0, hours: 3, pop: 9.1, desc: "Cypress lanes, rolling wheat, morning fog — Tuscany's most photographed valley." },
    { category: "wellness", name: "Tuscan Thermal Spa", city: "Montecatini", lat: 43.88, lng: 10.77, cost: 65, hours: 4, pop: 8.0, desc: "Art-nouveau terme: thermal pools, steam grottoes, and a very long lunch after." },
  ],
  events: [
    { name: "Calcio Storico Final", city: "Florence", start: "2026-06-24", end: "2026-06-24", cost: 30, source: "tourism-board:firenze", desc: "Renaissance-costume historic football in Piazza Santa Croce." },
    { name: "Arena di Verona Opera Festival", city: "Verona", start: "2026-06-12", end: "2026-09-05", cost: 60, source: "eventbrite", desc: "Nightly opera in the Roman arena all summer." },
    { name: "Luminara di San Ranieri", city: "Pisa", start: "2026-06-16", end: "2026-06-16", cost: 0, source: "tourism-board:pisa", desc: "70,000 candles light the Arno riverfront for one night." },
    { name: "Umbria Jazz Festival", city: "Perugia", start: "2026-07-10", end: "2026-07-19", cost: 40, source: "residentadvisor", desc: "Ten days of jazz across Perugia's old town." },
    { name: "Ravello Festival Opening", city: "Amalfi", start: "2026-06-28", end: "2026-08-30", cost: 45, source: "eventbrite", desc: "Symphonies on a terrace 350m above the Tyrrhenian Sea." },
    { name: "Taormina Film Fest", city: "Sicily", start: "2026-06-13", end: "2026-06-19", cost: 25, source: "eventbrite", desc: "Screenings in the ancient Greek theatre with Etna behind the screen." },
  ],
};
